### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by LukeAI** [baalexander/rospy_message_converter#23]
Hi, I have installed this package on Ubuntu 16.04 (ROS kinetic) via: sudo apt install ros-kinetic-rospy-message-converter

I have found that this works as expected if I try and use a dictionary only containing a single item called 'data', as in the readme.md example eg.
message = message_converter.convert_dictionary_to_ros_message('std_msgs/String', {'data': 'some_data' })

but if I attempt to convert any other dictionary, eg. message = message_converter.convert_dictionary_to_ros_message('std_msgs/String', {'mydata': 'some_data' })

I get:

ValueError: ROS message type "std_msgs/String" has no field named "mydata"

Any help in getting this to work would be very much appreciated.

**Comment by mintar** [comment]
This is because the data type `std_msgs/String` only has the field `data`: http://docs.ros.org/api/std_msgs/html/msg/String.html . The idea is that you provide a dictionary with the same fields as the message.

Maybe a different example: If you wanted to create a `sensor_msgs/Range` message (see http://docs.ros.org/api/sensor_msgs/html/msg/Range.html), your dictionary would look like this:

```python
d = {min_range: 1.0, max_range: 4.0, ...}
```

I hope that cleared things up for you.

**Comment by LukeAI** [comment]
Thanks, I think I misunderstood what this package was for. I thought that it would allow me to convert arbitrary dictionaries into strings and back again like https://docs.python.org/3/library/json.html but in such a way that I could also set header properties. I now realise that this isn't how ROS messages work and what I was really looking for was a way to define custom messages.

Your example and explanation is quite illustrative, I think that I would have got it if something like that were in the README. Could be a good addition?
